from qtile_extras.popup.toolkit import (
    PopupAbsoluteLayout,
    PopupText, PopupCircularProgress
)

from theme import Colours, Fonts


def block(x, y, w, h):
    return PopupText(
        background=Colours.bg_dim,
        foreground=Colours.bg_dim,
        highlight_radius=12,
        pos_x=x,
        pos_y=y,
        width=w,
        height=h,
    )


def diagnostic_controls():
    return [
        PopupText(
            name="battery_icon",
            font=Fonts.symbol,
            fontsize=25,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=110,
            pos_y=105,
            width=20,
            height=20,
            h_align="center",
        ),
        PopupText(
            name="battery_percentage",
            font=Fonts.sans + " Bold",
            fontsize=18,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=85,
            pos_y=135,
            width=70,
            height=20,
            h_align="center",
        ),
        PopupCircularProgress(
            name="battery_value",
            bar_size=12,
            start_angle=180,
            marker_size=0,
            marker_colour=Colours.fg,
            colour_below=Colours.green,
            colour_above=Colours.bg3,
            bar_border_colour=Colours.fg,
            pos_x=45,
            pos_y=55,
            width=150,
            height=150,
        ),
        PopupText(
            name="battery_time",
            font=Fonts.sans,
            fontsize=15,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=40,
            pos_y=220,
            width=160,
            height=15,
            h_align="center",
        ),
        PopupText(
            name="disk_icon",
            font=Fonts.symbol,
            fontsize=25,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=330,
            pos_y=105,
            width=20,
            height=20,
            h_align="center",
        ),
        PopupText(
            name="disk_percentage",
            font=Fonts.sans + " Bold",
            fontsize=18,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=305,
            pos_y=135,
            width=70,
            height=20,
            h_align="center",
        ),
        PopupCircularProgress(
            name="disk_value",
            bar_size=12,
            start_angle=180,
            marker_size=0,
            marker_colour=Colours.fg,
            colour_below=Colours.yellow,
            colour_above=Colours.bg3,
            bar_border_colour=Colours.fg,
            pos_x=265,
            pos_y=55,
            width=150,
            height=150,
        ),
        PopupText(
            name="disk_free",
            font=Fonts.sans,
            fontsize=15,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=260,
            pos_y=220,
            width=160,
            height=15,
            h_align="center",
        ),
        PopupText(
            name="cpu_icon",
            font=Fonts.symbol,
            fontsize=25,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=105,
            pos_y=350,
            width=30,
            height=20,
            h_align="center",
        ),
        PopupText(
            name="cpu_percentage",
            font=Fonts.sans + " Bold",
            fontsize=18,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=85,
            pos_y=380,
            width=70,
            height=20,
            h_align="center",
        ),
        PopupCircularProgress(
            name="cpu_value",
            bar_size=12,
            start_angle=180,
            marker_size=0,
            marker_colour=Colours.fg,
            colour_below=Colours.aqua,
            colour_above=Colours.bg3,
            bar_border_colour=Colours.fg,
            pos_x=45,
            pos_y=300,
            width=150,
            height=150,
        ),
        PopupText(
            name="ram_icon",
            font=Fonts.symbol,
            fontsize=25,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=325,
            pos_y=350,
            width=30,
            height=20,
            h_align="center",
        ),
        PopupText(
            name="ram_percentage",
            font=Fonts.sans + " Bold",
            fontsize=18,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=305,
            pos_y=380,
            width=70,
            height=20,
            h_align="center",
        ),
        PopupCircularProgress(
            name="ram_value",
            bar_size=12,
            start_angle=180,
            marker_size=0,
            marker_colour=Colours.fg,
            colour_below=Colours.blue,
            colour_above=Colours.bg3,
            bar_border_colour=Colours.fg,
            pos_x=265,
            pos_y=300,
            width=150,
            height=150,
        ),
        PopupText(
            text="󰈐",
            font=Fonts.symbol,
            fontsize=50,
            foreground=Colours.purple,
            background=Colours.bg_dim,
            pos_x=35,
            pos_y=550,
            width=50,
            height=40,
            h_align="center",
        ),
        PopupText(
            name="fan_speed",
            font=Fonts.sans + " Bold",
            fontsize=24,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=90,
            pos_y=550,
            width=140,
            height=40,
            h_align="center",
        ),
        PopupText(
            text="",
            font=Fonts.symbol,
            fontsize=50,
            foreground=Colours.red,
            background=Colours.bg_dim,
            pos_x=270,
            pos_y=550,
            width=50,
            height=40,
            h_align="center",
        ),
        PopupText(
            name="temp_value",
            font=Fonts.sans + " Bold",
            fontsize=24,
            foreground=Colours.fg,
            background=Colours.bg_dim,
            pos_x=320,
            pos_y=550,
            width=100,
            height=40,
            h_align="center",
        ),
    ]


def blocks():
    return [
        block(20, 20, 200, 235),    # Battery
        block(240, 20, 200, 235),   # Disk
        block(20, 275, 200, 200),   # CPU
        block(240, 275, 200, 200),  # RAM
        block(20, 500, 220, 140),   # Fan
        block(260, 500, 180, 140),  # Temperature
    ]


def diagnostics_popup():
    return PopupAbsoluteLayout(
        width=460,
        height=660,
        background=Colours.bg1,
        border=Colours.bg1,
        border_width=0,
        controls=[*blocks(), *diagnostic_controls()],
        hide_on_timeout=0,
        close_on_click=True,
    )
