import os
from libqtile.lazy import lazy
from qtile_extras.popup import toolkit as popup
from os.path import expanduser

from theme import Colours, Fonts


DEFAULT = os.path.expanduser("~/.config/qtile/assets/none.png")


###################
# Helper functions
###################

def _wnet(i):
    return [
        popup.PopupText(
            name=f"wnet_{i}_ssid",
            font=Fonts.mono,
            fontsize=12,
            foreground=Colours.text,
            background=Colours.surface,
            pos_x=30,
            pos_y=475+i*25,
            width=120,
            height=10,
            h_align="left",
        ),
        popup.PopupText(
            name=f"wnet_{i}_signal",
            font=Fonts.sans,
            fontsize=10,
            foreground=Colours.muted,
            background=Colours.surface,
            pos_x=155,
            pos_y=475+i*25,
            width=40,
            height=10,
            h_align="center",
        ),
        popup.PopupText(
            name=f"wnet_{i}_security",
            font=Fonts.mono,
            fontsize=12,
            foreground=Colours.muted,
            background=Colours.surface,
            pos_x=200,
            pos_y=475+i*25,
            width=30,
            height=10,
            h_align="left",
        )]


def _bt_dev(i):
    return [
        popup.PopupText(
            name=f"bt_dev_{i}_name",
            font=Fonts.mono,
            fontsize=12,
            foreground=Colours.text,
            background=Colours.surface,
            pos_x=270,
            pos_y=475+i*25,
            width=120,
            height=10,
            h_align="left",
        ),
        popup.PopupText(
            name=f"bt_dev_{i}_status",
            font=Fonts.sans,
            fontsize=12,
            foreground=Colours.muted,
            background=Colours.surface,
            pos_x=395,
            pos_y=475+i*25,
            width=50,
            height=10,
            h_align="center",
        )]


def _core(i):
    return popup.PopupText(
        text=f"Core {i}",
        font=Fonts.sans,
        fontsize=15,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=465+i*30,
        width=50,
        height=10,
        h_align="center",
    ), popup.PopupSlider(
        name=f"cpu_core_{i}",
        bar_size=10,
        marker_size=0,
        colour_below=Colours.iris,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        bar_border_margin=0,
        end_margin=0,
        pos_x=110,
        pos_y=465+i*30,
        width=110,
        height=10
    )


def _process(i):
    return popup.PopupText(
        name=f"process_{i}_name",
        font=Fonts.mono,
        fontsize=12,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=275,
        pos_y=215+i*30,
        width=60,
        height=10,
        h_align="center",
    ), popup.PopupSlider(
        name=f"process_{i}_memory",
        bar_size=10,
        marker_size=0,
        colour_below=Colours.iris,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        bar_border_margin=0,
        end_margin=0,
        pos_x=340,
        pos_y=215+i*30,
        width=100,
        height=10
    )


####################
# Component batches
####################

battery_components = [
    popup.PopupText(
        name="battery_icon",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=120,
        pos_y=105,
        width=20,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="battery_percentage",
        font=Fonts.sans + " Bold",
        fontsize=18,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=95,
        pos_y=135,
        width=70,
        height=20,
        h_align="center",
    ),
    popup.PopupCircularProgress(
        name="battery_value",
        bar_size=12,
        start_angle=180,
        marker_size=0,
        marker_colour=Colours.text,
        colour_below=Colours.pine,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        pos_x=55,
        pos_y=55,
        width=150,
        height=150,
    ),
    popup.PopupText(
        name="battery_time",
        font=Fonts.sans,
        fontsize=15,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=50,
        pos_y=220,
        width=160,
        height=15,
        h_align="center",
    ),
]

cpu_components = [
    popup.PopupText(
        name="cpu_icon",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=115,
        pos_y=355,
        width=30,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="cpu_percentage",
        font=Fonts.sans + " Bold",
        fontsize=18,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=95,
        pos_y=385,
        width=70,
        height=20,
        h_align="center",
    ),
    popup.PopupCircularProgress(
        name="cpu_value",
        bar_size=12,
        start_angle=180,
        marker_size=0,
        marker_colour=Colours.text,
        colour_below=Colours.sky,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        pos_x=55,
        pos_y=305,
        width=150,
        height=150,
    ),
    *_core(1),
    *_core(2),
    *_core(3),
    *_core(4),
    *_core(5),
    *_core(6),
    *_core(7),
    *_core(8),
]

ram_components = [
    popup.PopupText(
        name="ram_icon",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=345,
        pos_y=105,
        width=30,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="ram_percentage",
        font=Fonts.sans + " Bold",
        fontsize=18,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=325,
        pos_y=135,
        width=70,
        height=20,
        h_align="center",
    ),
    popup.PopupCircularProgress(
        name="ram_value",
        bar_size=12,
        start_angle=180,
        marker_size=0,
        marker_colour=Colours.text,
        colour_below=Colours.blue,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        pos_x=285,
        pos_y=55,
        width=150,
        height=150,
    ),
    *_process(1),
    *_process(2),
    *_process(3),
    *_process(4),
    *_process(5),
    *_process(6),
    *_process(7),
    *_process(8),
    *_process(9),
]

disk_components = [
    popup.PopupText(
        name="disk_icon",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=350,
        pos_y=630,
        width=20,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="disk_percentage",
        font=Fonts.sans + " Bold",
        fontsize=18,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=325,
        pos_y=660,
        width=70,
        height=20,
        h_align="center",
    ),
    popup.PopupCircularProgress(
        name="disk_value",
        bar_size=12,
        start_angle=180,
        marker_size=0,
        marker_colour=Colours.text,
        colour_below=Colours.yellow,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        pos_x=285,
        pos_y=580,
        width=150,
        height=150,
    ),
]

fan_components = [
    popup.PopupText(
        text="󰈐",
        font=Fonts.symbol,
        fontsize=50,
        foreground=Colours.mauve,
        background=Colours.surface,
        pos_x=45,
        pos_y=825,
        width=50,
        height=40,
        h_align="center",
    ),
    popup.PopupText(
        name="fan_speed",
        font=Fonts.sans + " Bold",
        fontsize=24,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=100,
        pos_y=825,
        width=130,
        height=40,
        h_align="center",
    ),
]

temperature_components = [
    popup.PopupText(
        text="",
        font=Fonts.symbol,
        fontsize=50,
        foreground=Colours.maroon,
        background=Colours.surface,
        pos_x=290,
        pos_y=825,
        width=50,
        height=40,
        h_align="center",
    ),
    popup.PopupText(
        name="temp_value",
        font=Fonts.sans + " Bold",
        fontsize=24,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=340,
        pos_y=825,
        width=100,
        height=40,
        h_align="center",
    ),
]

powermenu_components = [
    popup.PopupText(
        text="",
        pos_x=40,
        pos_y=955,
        width=85,
        height=85,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=32,
        font=Fonts.symbol,
        highlight=Colours.blue,
        mouse_callbacks={
            "Button1": lazy.spawn(expanduser("~/.local/bin/lock"))
        },
    ),
    popup.PopupText(
        text="",
        pos_x=145,
        pos_y=955,
        width=85,
        height=85,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=33,
        font=Fonts.symbol,
        highlight=Colours.blue,
        mouse_callbacks={
            "Button1": lazy.shutdown()
        },
    ),
    popup.PopupText(
        text="",
        pos_x=250,
        pos_y=955,
        width=85,
        height=85,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=34,
        font=Fonts.symbol,
        highlight=Colours.blue,
        mouse_callbacks={
            "Button1": lazy.spawn("reboot")
        },
    ),
    popup.PopupText(
        text="󰐥",
        pos_x=355,
        pos_y=955,
        width=85,
        height=85,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=38,
        font=Fonts.symbol,
        highlight=Colours.blue,
        mouse_callbacks={
            "Button1": lazy.spawn("shutdown now")
        },
    ),
]

wifi_components = [
    popup.PopupText(
        text="󰤨",
        font=Fonts.symbol,
        fontsize=45,
        foreground=Colours.green,
        background=Colours.surface,
        pos_x=100,
        pos_y=80,
        width=60,
        height=40,
        h_align="center",
    ),
    popup.PopupText(
        name="wifi_ssid",
        font=Fonts.sans + " Bold",
        fontsize=14,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=130,
        width=180,
        height=15,
        h_align="center",
    ),
    popup.PopupText(
        name="wifi_status",
        font=Fonts.sans,
        fontsize=12,
        foreground=Colours.subtext1,
        background=Colours.surface,
        pos_x=40,
        pos_y=180,
        width=180,
        height=12,
        h_align="center",
    ),
    popup.PopupSlider(
        name="wifi_signal_strength",
        bar_size=8,
        marker_size=0,
        colour_below=Colours.green,
        colour_above=Colours.overlay,
        bar_border_colour=Colours.text,
        bar_border_margin=0,
        end_margin=0,
        pos_x=60,
        pos_y=160,
        width=140,
        height=8,
    ),
]

ethernet_components = [
    popup.PopupText(
        text="󰈀",
        font=Fonts.symbol,
        fontsize=45,
        foreground=Colours.peach,
        background=Colours.surface,
        pos_x=330,
        pos_y=80,
        width=60,
        height=40,
        h_align="center",
    ),
    popup.PopupText(
        name="ethernet_status",
        font=Fonts.sans + " Bold",
        fontsize=14,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=270,
        pos_y=130,
        width=180,
        height=15,
        h_align="center",
    ),
    popup.PopupText(
        name="ethernet_speed",
        font=Fonts.sans,
        fontsize=12,
        foreground=Colours.subtext1,
        background=Colours.surface,
        pos_x=270,
        pos_y=160,
        width=180,
        height=12,
        h_align="center",
    ),
    popup.PopupText(
        name="ethernet_ip",
        font=Fonts.mono,
        fontsize=10,
        foreground=Colours.subtext0,
        background=Colours.surface,
        pos_x=270,
        pos_y=180,
        width=180,
        height=10,
        h_align="center",
    ),
]

connection_components = [
    popup.PopupText(
        text="",
        font=Fonts.symbol,
        fontsize=45,
        foreground=Colours.blue,
        background=Colours.surface,
        pos_x=100,
        pos_y=310,
        width=60,
        height=40,
        h_align="center",
    ),
    popup.PopupText(
        name="internet_status",
        font=Fonts.sans + " Bold",
        fontsize=14,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=360,
        width=180,
        height=15,
        h_align="center",
    ),
    popup.PopupText(
        name="dns_servers",
        font=Fonts.mono,
        fontsize=11,
        foreground=Colours.subtext0,
        background=Colours.surface,
        pos_x=40,
        pos_y=385,
        width=180,
        height=12,
        h_align="center",
    ),
]

bluetooth_components = [
    popup.PopupText(
        text="󰂯",
        font=Fonts.symbol,
        fontsize=45,
        foreground=Colours.mauve,
        background=Colours.surface,
        pos_x=330,
        pos_y=320,
        width=60,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="bt_status",
        font=Fonts.sans + " Bold",
        fontsize=14,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=270,
        pos_y=360,
        width=180,
        height=15,
        h_align="center",
    ),
    popup.PopupText(
        name="bt_connected_count",
        font=Fonts.mono,
        fontsize=11,
        foreground=Colours.subtext0,
        background=Colours.surface,
        pos_x=270,
        pos_y=385,
        width=180,
        height=12,
        h_align="center",
    ),
]

available_wifi_components = [
    popup.PopupText(
        text="Available Networks",
        font=Fonts.sans + " Bold",
        fontsize=15,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=30,
        pos_y=450,
        width=200,
        height=12,
        h_align="left",
    ),
    *_wnet(0),
    *_wnet(1),
    *_wnet(2),
    *_wnet(3),
    *_wnet(4),
    *_wnet(5),
]

available_bt_components = [
    popup.PopupText(
        text="Bluetooth Devices",
        font=Fonts.sans + " Bold",
        fontsize=15,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=270,
        pos_y=450,
        width=180,
        height=12,
        h_align="left",
    ),
    *_bt_dev(0),
    *_bt_dev(1),
    *_bt_dev(2),
    *_bt_dev(3),
    *_bt_dev(4),
    *_bt_dev(5),
]

applet_components = [
    popup.PopupText(
        text="󰒓",
        pos_x=40,
        pos_y=780,
        width=85,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=24,
        font=Fonts.symbol,
        highlight=Colours.blue,
        mouse_callbacks={
            "Button1": lazy.spawn("nm-connection-editor")
        },
    ),
    popup.PopupText(
        text="Network\nManager",
        pos_x=40,
        pos_y=860,
        width=85,
        height=20,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="󰤨",
        pos_x=145,
        pos_y=780,
        width=85,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=24,
        font=Fonts.symbol,
        highlight=Colours.green,
        mouse_callbacks={
            "Button1": lazy.widget["netmasterwidget"].refresh_status()
        },
    ),
    popup.PopupText(
        text="Refresh\nNetworks",
        pos_x=145,
        pos_y=860,
        width=85,
        height=20,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="󰂳",
        pos_x=250,
        pos_y=780,
        width=85,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=24,
        font=Fonts.symbol,
        highlight=Colours.mauve,
        mouse_callbacks={
            "Button1": lazy.spawn("blueman-manager")
        },
    ),
    popup.PopupText(
        text="Bluetooth\nManager",
        pos_x=250,
        pos_y=860,
        width=85,
        height=20,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="",
        pos_x=355,
        pos_y=780,
        width=85,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=24,
        font=Fonts.symbol,
        highlight=Colours.yellow,
        mouse_callbacks={
            "Button1": lazy.spawn("kitty -e nmtui")
        },
    ),
    popup.PopupText(
        text="Network\nTUI",
        pos_x=355,
        pos_y=860,
        width=85,
        height=20,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
]

toggle_components = [
    popup.PopupText(
        text="󰤭",
        pos_x=40,
        pos_y=940,
        width=120,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=28,
        font=Fonts.symbol,
        highlight=Colours.sky,
        mouse_callbacks={
            "Button1": lazy.spawn("nmcli radio wifi off"),
            "Button3": lazy.spawn("nmcli radio wifi on")
        },
    ),
    popup.PopupText(
        text="Toggle WiFi",
        pos_x=40,
        pos_y=1010,
        width=120,
        height=10,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="󰂲",  # Bluetooth toggle icon
        pos_x=180,
        pos_y=940,
        width=120,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=28,
        font=Fonts.symbol,
        highlight=Colours.mauve,
        mouse_callbacks={
            "Button1": lazy.spawn("bluetoothctl power off"),
            "Button3": lazy.spawn("bluetoothctl power on")
        },
    ),
    popup.PopupText(
        text="Toggle Bluetooth",
        pos_x=180,
        pos_y=1010,
        width=120,
        height=10,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="",  # Airplane mode icon
        pos_x=320,
        pos_y=940,
        width=120,
        height=60,
        h_align="center",
        foreground=Colours.crust,
        background=Colours.subtext0,
        fontsize=28,
        font=Fonts.symbol,
        highlight=Colours.red,
        mouse_callbacks={
            "Button1": lazy.spawn("rfkill block all"),
            "Button3": lazy.spawn("rfkill unblock all")
        },
    ),
    popup.PopupText(
        text="Airplane Mode",
        pos_x=320,
        pos_y=1010,
        width=120,
        height=10,
        h_align="center",
        foreground=Colours.text,
        background=Colours.surface,
        fontsize=12,
        font=Fonts.sans,
    ),
    popup.PopupText(
        text="Left-click to toggle on and Right-click to toggle off",
        pos_x=40,
        pos_y=1040,
        width=400,
        height=10,
        h_align="center",
        fontsize=12,
        font=Fonts.sans,
        foreground=Colours.text,
        background=Colours.surface,
    ),
]

today_components = [
    popup.PopupText(
        name="current_day",
        font=Fonts.sans + " Bold",
        fontsize=56,
        foreground=Colours.mauve,
        background=Colours.surface,
        pos_x=40,
        pos_y=40,
        width=400,
        height=120,
        h_align="center",
    ),
    popup.PopupText(
        name="current_date",
        font=Fonts.sans + " Medium",
        fontsize=25,
        foreground=Colours.lavender,
        background=Colours.surface,
        pos_x=40,
        pos_y=160,
        width=400,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="current_month",
        font=Fonts.sans + " Bold",
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=90,
        pos_y=260,
        width=300,
        height=30,
        h_align="center",
    ),
]

calendar_components = [
    popup.PopupText(
        text="",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=370,
        pos_y=260,
        width=50,
        height=30,
        h_align="center",
        mouse_callbacks={"Button1": lambda x: None},
        highlight=Colours.surface,
    ),
    popup.PopupText(
        text="",
        font=Fonts.symbol,
        fontsize=25,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=260,
        width=50,
        height=30,
        h_align="center",
        mouse_callbacks={"Button1": lambda x: None},
        highlight=Colours.surface,
    ),
] + [
    popup.PopupText(
        name=f"day_{i}_{ii}",
        foreground=Colours.text,
        background=Colours.crust if ii == 6 else Colours.mantle,
        fontsize=18,
        font=Fonts.sans + " Medium",
        markup=True,
        width=50,
        height=50,
        pos_x=35 + ii*60,
        pos_y=350 + i*60,
        h_align="center",
    )
    for i in range(6)
    for ii in range(7)
] + [
    popup.PopupText(
        name=f"weekday_{i}",
        foreground=Colours.text,
        background=Colours.crust if i == 6 else Colours.mantle,
        fontsize=18,
        font=Fonts.sans + " Medium",
        markup=True,
        width=50,
        height=30,
        pos_x=35 + i*60,
        pos_y=310,
        h_align="center",
    )
    for i in range(7)
]

music_components = [
    popup.PopupImage(
        name="music_cover",
        filename=DEFAULT,
        background=Colours.surface,
        pos_x=40,
        pos_y=760,
        width=260,
        height=160,
        h_align="center",
    ),
    popup.PopupText(
        name="music_title",
        font=Fonts.sans + " Bold",
        fontsize=20,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=940,
        width=260,
        height=20,
        h_align="center",
    ),
    popup.PopupText(
        name="music_artist",
        font=Fonts.sans + " Medium",
        fontsize=18,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=40,
        pos_y=960,
        width=260,
        height=20,
        h_align="center",
    ),
]

volbright_components = [
    popup.PopupSlider(
        name="volume_value",
        horizontal=False,
        bar_size=20,
        end_margin=0,
        marker_size=0,
        colour_below=Colours.green,
        colour_above=Colours.surface1,
        pos_y=760,
        pos_x=370,
        height=240,
        width=20,
    ),
    popup.PopupText(
        name="volume_icon",
        font=Fonts.symbol,
        fontsize=28,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=365,
        pos_y=1015,
        width=30,
        height=20,
        h_align="center",
    ),
    popup.PopupSlider(
        name="brightness_value",
        horizontal=False,
        bar_size=20,
        end_margin=0,
        marker_size=0,
        colour_below=Colours.pink,
        colour_above=Colours.surface1,
        pos_y=760,
        pos_x=410,
        height=240,
        width=20,
    ),
    popup.PopupText(
        name="brightness_icon",
        font=Fonts.symbol,
        fontsize=28,
        foreground=Colours.text,
        background=Colours.surface,
        pos_x=405,
        pos_y=1015,
        width=30,
        height=20,
        h_align="center",
    ),
]


########################
# Diagnostics sidebar
########################

_diagnostics = [
    *battery_components,
    *cpu_components,
    *ram_components,
    *disk_components,
    *fan_components,
    *temperature_components,
    *powermenu_components,
]


########################
# Network sidebar
########################

_network = [
    *wifi_components,
    *ethernet_components,
    *connection_components,
    *bluetooth_components,
    *available_wifi_components,
    *available_bt_components,
    *applet_components,
    *toggle_components,
]


########################
# Datetime sidebar
########################

_datetime = [
    *today_components,
    *calendar_components,
    *music_components,
    *volbright_components,
]
