#################################
#         Visual Effects        #
#################################

rules = (
  { match = "!QTILE_INTERNAL"; corner-radius = 4; shadow = True; },
  { match = "QTILE_INTERNAL"; corner-radius = 0; shadow = False; },
  { match = "fullscreen"; corner-radius = 0; },
);

shadow-radius = 10;
shadow-offset-x = -10;
shadow-offset-y = -10;

#################################
#           Animations          #
#################################

animations = ({
  triggers = ["open", "show"];
  preset = "slide-in";
},
{
  triggers = ["close", "hide"];
  preset = "slide-out";
},
{
  triggers = ["geometry"];
  preset = "geometry-change";
});

#################################
#       General Settings        #
#################################

dbus = true
backend = "glx";
dithered-present = false;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = true;
transparent-clipping = false
log-level = "warn";
