palette = "catppuccin_mocha"

format = """
[▋](fg:blue) $character  $directory $git_branch$cmd_duration $fill [▋](fg:blue)
[  ](fg:green)
"""
add_newline = false

[directory]
format = "[$path](bg:base fg:rosewater bold)"
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"~/Documents" = "󰈙 "
"~/Downloads" = " "
"~/.config" = " "

[git_branch]
symbol = ""
format = " [$symbol $branch](bg:base fg:subtext0) "

[cmd_duration]
format = "| [$duration](bg:base fg:green)"
min_time = 500

[character]
format = "$symbol"
success_symbol = "[](bg:base fg:green bold)"
error_symbol = "[](bg:base fg:green bold)"
vimcmd_symbol = "[](bg:base fg:red bold)"

[fill]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
