[colors]
background = #282A36
background-alt = #44475A
foreground = #F8F8F2

cyan = #8BE9FD
green = #50FA7B
yellow = #F1FA8C
orange = #FFB86C
red = #FF5555
pink = #FF79C6
purple = #BD93F9

primary = ${colors.cyan}
secondary = ${colors.green}
alert = ${colors.red}
disabled = ${colors.background-alt}

[bar/mybar]
width = 100%
height = 22pt
radius = 00

; dpi = 96

background = #00282A36
foreground = ${colors.background}

line-size = 3pt

border-size = 0pt
border-color = ${colors.purple}

font-0 = Fira Code:size=11;2
font-1 = Cascadia Code PL:size=17;6
font-2 = Fira Code:size=11:weight=100;2

modules-left = xworkspaces memory cpu 
modules-center = date
modules-right = pulseaudio wlan eth

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right
tray-background = ${colors.background-alt}
; tray-offset-x = -8

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.secondary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1
label-occupied-background = ${colors.background-alt}
label-occupied-foreground = ${colors.foreground}

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-foreground = ${colors.foreground}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

; [module/xwindow]
; type = internal/xwindow
; label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = %{T2}%{T-}
;format-volume-prefix = %{T2}%{T-}
;format-volume-prefix-foreground = ${colors.green}
format-volume-prefix-foreground = ${colors.background-alt}
;format-volume-suffix = %{T2} %{T-}
format-volume-suffix = %{T2} %{T-}
format-volume-suffix-background = ${colors.background-alt}
format-volume-suffix-foreground = ${colors.background}
;format-volume-suffix = %{T2}%{T-}
;format-volume-suffix-foreground = ${colors.orange}
;format-volume-suffix-background = ${colors.green}
format-volume = <label-volume>

label-volume = %{T1} %{T-}VOL %percentage%% 
;label-volume-background = ${colors.green}
label-volume-background = ${colors.background-alt}
label-volume-foreground = ${colors.foreground}

format-muted-prefix = %{T2}%{T-}
;format-muted-prefix = %{T2} %{T-}
;format-muted-prefix-foreground = ${colors.green}
format-muted-prefix-foreground = ${colors.background-alt}
;format-muted-suffix = %{T2} %{T-}
format-muted-suffix = %{T2} %{T-}
format-muted-suffix-background = ${colors.background-alt}
format-muted-suffix-foreground = ${colors.background}
;format-muted-suffix = %{T2} %{T-}
;format-muted-suffix-foreground = ${colors.orange}
;format-muted-suffix-background = ${colors.green}
format-muted = <label-muted>

label-muted = VOL muted 
;label-muted-background = ${colors.green}
label-muted-background = ${colors.background-alt}
label-muted-foreground = ${colors.foreground}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
label = %{T1} RAM %percentage_used:2%%
;label-background = ${colors.yellow}
label-background = ${colors.background-alt}
label-foreground = ${colors.foreground}
format-prefix = %{T2} %{T-}
;format-prefix = %{T2}%{T-}
format-prefix-foreground = ${colors.background}
format-prefix-background = ${colors.background-alt}
;format-suffix = %{T2}%{T-}
format-suffix = %{T2} %{T-}
format-suffix-foreground = ${colors.background}
format-suffix-background = ${colors.background-alt}

[module/cpu]
type = internal/cpu
interval = 2
label-background = ${colors.background-alt}
;label-background = ${colors.purple}
label-foreground = ${colors.foreground}
;label-foreground = ${colors.background}
label = %{T1}  CPU%percentage:3%% %{T1} %{T-}
format-suffix = %{T2}%{T-}
format-suffix-foreground = ${colors.background-alt}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %ifname%% %essid% %upspeed:9% %downspeed:9% %{F#44475a T2}%{F- T-}
;label-connected = %ifname%% %essid% %upspeed:9% %downspeed:9% %{F#44475a T2}%{F- T-}
;label-connected-background = ${colors.orange}
label-connected-background = ${colors.background-alt}
label-connected-foreground = ${colors.foreground}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = ↑%upspeed:9%  ↓%downspeed:9% %{F#282A36 T2} %{F- T-}
;label-connected = %upspeed:9% %downspeed:9% %{F#44475a T2}%{F- T-}
;label-connected = %upspeed:9% %downspeed:9% %{F#44475a T2}%{F- T-}
;label-connected-background = ${colors.orange}
label-connected-background = ${colors.background-alt}
label-connected-foreground = ${colors.foreground}

[module/date]
type = internal/date
interval = 1

date-alt = %{T3}%D %H:%M:%S%{T-}
date = %{T3}%A, %d %B %Y %H:%M:%S%{T-}

format-prefix = %{T2}%{T-}
format-prefix-foreground = ${colors.primary}
format-suffix = %{T2}%{T-}
format-suffix-foreground = ${colors.primary}

label = %date%
label-background = ${colors.primary}
label-foreground = ${colors.background}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
