pacman:
  fonts:
    - "noto-fonts"
    - "noto-fonts-cjk"
    - "noto-fonts-emoji"
    - "noto-fonts-extra"
    - "tex-gyre-fonts"
    - "ttc-iosevka"
    - "ttf-nerd-fonts-symbols"
    - "inter-font"
  network:
    - "blueman"
    - "bluez"
    - "bluez-utils"
    - "networkmanager"
    - "wpa_supplicant"
    - "iwd"
  imp:
    - "base"
    - "base-devel"
    - "alsa-firmware"
    - "alsa-utils"
    - "atool"
    - "brightnessctl"
    - "btop"
    - "calibre"
    - "discord"
    - "docker"
    - "docker-compose"
    - "dunst"
    - "efibootmgr"
    - "emacs"
    - "flameshot"
    - "fish"
    - "gimp"
    - "grub"
    - "i3lock-color"
    - "inkscape"
    - "kdeconnect"
    - "kicad"
    - "kitty"
    - "libreoffice-fresh"
    - "lxappearance"
    - "matugen-bin"
    - "meson"
    - "mpv"
    - "neovim"
    - "obs-studio"
    - "openscad"
    - "openssh"
    - "openvpn"
    - "picom"
    - "qtile"
    - "ranger"
    - "rofi"
    - "rclone"
    - "redshift"
    - "rsync"
    - "scrcpy"
    - "sof-firmware"
    - "spotify"
    - "steam"
    - "syncthing"
    - "trash-cli"
    - "tree-sitter-cli"
    - "mesa-utils"
    - "npm"
    - "xcape"
    - "wlroots"
    - "wayland"
    - "xdg-desktop-portal-gtk"
    - "zathura"
    - "zathura-pdf-mupdf"
  audio:
    - "pamixer"
    - "pavucontrol"
    - "pipewire"
    - "pipewire-pulse"
    - "pipewire-jack"
    - "pipewire-alsa"
  python:
    - "python"
    - "uv"
  graphics:
    - "mesa"
    - "mesa-utils"
    - "vulkan-intel"
    - "vulkan-tools"
  
  
aur:
  - "decman"
  - "decklink"
  - "brave-bin"
  - "equibop"
  - "proton-ge-custom-bin"
  - "qtile-extras"
  - "spicetify-cli"
  - "zen-browser-bin"
  - "zotero-bin"

ignore:
  - "yay"

systemd:
  units:
    - "NetworkManager.service"
    - "bluetooth.service"
    - "docker.service"
